### PR TITLE
Adapter Pattern.

### PR DESCRIPTION
**Pull request by AlexanderVladimirov9090**
Done.

### CODE REVIEW

**Comment by AlexanderVladimirov9090** [comment]
Done.

**Comment by mgenov** [comment]
You need to squash your commits.

**Comment by mgenov** [comment]
https://github.com/clouway/teamspace/wiki/Repositories

**Comment by AlexanderVladimirov9090** [comment]
Will be done.

**Comment by AlexanderVladimirov9090** [comment]
Done.

**Pull request merged**
