### PR TITLE
Singleton pattern.

### PR DESCRIPTION
**Pull request by AlexanderVladimirov9090**
Done with singleton pattern.

### CODE REVIEW

**Comment by AlexanderVladimirov9090** [comment]
Done.

**Comment by AlexanderVladimirov9090** [comment]
Will be done.

**Comment by AlexanderVladimirov9090** [comment]
Done.

**Comment by mgenov** [comment]
"Done with Singleton" is really bad message.

**Comment by mgenov** [comment]
Seems not done. 

screen shot 2016-10-27 at 1 52 30 pm

**Comment by AlexanderVladimirov9090** [comment]
Will fix it.

**Comment by AlexanderVladimirov9090** [comment]
Done.

**Comment by mgenov** [comment]
The commit is worse then it was before ! 

This is how commit should look like: 
screen shot 2016-10-27 at 2 13 54 pm

**Pull request merged**
